# Generated by Django 5.0.4 on 2024-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='people_apply',
            field=models.IntegerField(default=0),
        ),
    ]
