# Generated by Django 5.0.4 on 2024-04-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0004_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
