# Generated by Django 5.0.4 on 2024-04-24 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0006_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='helper',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='i_helped', to=settings.AUTH_USER_MODEL),
        ),
    ]
