# Generated by Django 5.0.4 on 2024-04-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0007_post_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
    ]
