# Generated by Django 5.0.4 on 2024-04-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0008_alter_post_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
    ]
