# Generated by Django 5.0.4 on 2024-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0011_remove_post_blood_need_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blood_need_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
