# Generated by Django 5.0.4 on 2024-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0012_post_blood_need_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='impage2',
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
