# Generated by Django 5.0.4 on 2024-04-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0013_remove_post_impage2_post_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='impage1',
            new_name='image1',
        ),
    ]
