# Generated by Django 5.0.4 on 2024-04-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_object', '0014_rename_impage1_post_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/post'),
        ),
    ]
